server.port=8080

# Railway PostgreSQL
spring.datasource.url=jdbc:postgresql://yamabiko.proxy.rlwy.net:55603/railway
spring.datasource.username=postgres
spring.datasource.password=mZLqeBZhSOPNjibzAcfvTBLlSNoEOrYz
spring.datasource.driver-class-name=org.postgresql.Driver

# MyBatis
mybatis.configuration.map-underscore-to-camel-case=true

# ????????????
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql