server.port=8080

# ? Railway ??????
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# MyBatis
mybatis.configuration.map-underscore-to-camel-case=true

# ??? SQL????????? always???? never?
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# ???
spring.datasource.hikari.maximum-pool-size=5