server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://yamabiko.proxy.rlwy.net:57337/railway?sslmode=require
    username: postgres
    password: QUenofsRzuMAxNeXbKoArOSPHEQfuHER
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  sql:
    init:
      mode: always  # 保持always，自动建表

mybatis:
  configuration:
    map-underscore-to-camel-case: true