server.port=8080

spring.datasource.url=jdbc:postgresql://yamabiko.proxy.rlwy.net:55603/railway
spring.datasource.username=postgres
spring.datasource.password=f1project2026
spring.datasource.driver-class-name=org.postgresql.Driver

# MyBatis
mybatis.configuration.map-underscore-to-camel-case=true

# ?? SQL ???
spring.sql.init.mode=never

# ???
spring.datasource.hikari.maximum-pool-size=5